[BTAT-9181]-Removal of Stub Contact Preferences feature
hmrc/deregister-vat-frontend pull request #289
Opened 2021-04-29 08:21 UTC by william-hatzar

# Pull Request Checklist
* [x] Branch is rebased with master
* [ ] Added Unit Tests for changed functionality
* [x] Ran `sbt clean compile coverage test it:test coverageReport`, all tests pass and coverage meets minimum
* [ ] Checked libraries are up to date with `sbt validate`. (If applicable) library updates are done in a separate, single commit
* [x] Ran [change-vat-acceptance-tests](https://github.com/hmrc/change-vat-acceptance-tests) (see README of repo)
* [ ] Ran [change-vat-performance-tests](https://github.com/hmrc/change-vat-performance-tests) (see README of repo)
* [x] (If applicable) raised app-config-* PRs
* [ ] (If applicable) ran Wave test for changes to views
* [ ] (If applicable) added Integration Tests

App Config QA  -> https://github.com/hmrc/app-config-qa/pull/11448

2021-04-29 12:44 UTC, lewishay requested changes

2021-04-29 12:44 UTC, lewishay commented on app/config/frontendAppConfig.scala
> -    if (features.stubContactPreferences()) {
Now that we get contact prefs from our customer info call (a call to `vat-subscription` that is already configured and set up), this `contactPreferencesService` val as a whole is not needed.

There are a few other things that you can also now remove:
- The `contactPreferencesUrl` function below
- The `contact-preferences` config from `application.conf`
- The corresponding val in `ConfigKeys`

2021-04-30 09:12 UTC, lewishay approved these changes
Approved awaiting clear pipeline and config PR merges

2021-04-30 09:17 UTC, william-hatzar commented
App Config Base PR- https://github.com/hmrc/app-config-base/pull/5571

2021-04-30 10:36 UTC, merged