Btat 9224 Play 2.8 upgrade
hmrc/deregister-vat-frontend pull request #292
Opened 2021-05-28 10:42 UTC by JoNB7777

# Pull Request Checklist
* [x] Branch is rebased with master
* [ ] Added Unit Tests for changed functionality
* [x] Ran `sbt clean compile coverage test it:test coverageReport`, all tests pass and coverage meets minimum
* [ ] Checked libraries are up to date with `sbt validate`. (If applicable) library updates are done in a separate, single commit
* [x] Ran [change-vat-acceptance-tests](https://github.com/hmrc/change-vat-acceptance-tests) (see README of repo)
* [ ] Ran [change-vat-performance-tests](https://github.com/hmrc/change-vat-performance-tests) (see README of repo)
* [ ] (If applicable) raised app-config-* PRs
* [ ] (If applicable) ran Wave test for changes to views
* [ ] (If applicable) added Integration Tests

2021-06-01 15:48 UTC, william-hatzar commented on build.sbt
>    "uk.gov.hmrc"   %% "govuk-template"                  % "5.66.0-play-26",
This can be removed as it is no longer needed

2021-06-01 15:48 UTC, william-hatzar commented on build.sbt
> -  "uk.gov.hmrc"   %% "play-ui"                         % "9.2.0-play-26",
Can be bumped to play 28

2021-06-01 15:48 UTC, william-hatzar commented on build.sbt
>    "uk.gov.hmrc"   %% "play-partials"                   % "7.1.0-play-26",
can be bumped to play 28

2021-06-01 15:48 UTC, william-hatzar commented on build.sbt
> -  "uk.gov.hmrc"   %% "play-language"                   % "4.12.0-play-26",
Same as the others

2021-06-01 15:48 UTC, william-hatzar commented on build.sbt
> -  "uk.gov.hmrc"   %% "play-frontend-govuk"             % "0.71.0-play-26",
Same as the others

2021-06-01 15:48 UTC, william-hatzar commented on build.sbt
> -  "uk.gov.hmrc"   %% "play-frontend-hmrc"              % "0.57.0-play-26",
Same as the others

2021-06-01 15:48 UTC, william-hatzar commented on app/utils/LoggerUtil.scala
> +
These logs don't seem to be showing in the terminal when I run through the journey

2021-06-02 13:28 UTC, william-hatzar commented on build.sbt
>    "uk.gov.hmrc"   %% "govuk-template"                  % "5.66.0-play-26",
This can be removed

2021-06-02 13:28 UTC, william-hatzar commented on build.sbt
> +  "uk.gov.hmrc"   %% "play-ui"                         % "9.4.0-play-26",
Can be bumped to play-28

2021-06-02 13:28 UTC, william-hatzar commented on build.sbt
>    "uk.gov.hmrc"   %% "play-partials"                   % "7.1.0-play-26",
Can be bumped to play-28

2021-06-02 13:28 UTC, william-hatzar commented on build.sbt
> +  "uk.gov.hmrc"   %% "play-language"                   % "5.0.0-play-26",
Same as the others

2021-06-02 13:28 UTC, william-hatzar commented on build.sbt
> +  "uk.gov.hmrc"   %% "play-frontend-govuk"             % "0.73.0-play-26",
Same as the others

2021-06-02 13:28 UTC, william-hatzar commented on build.sbt
> +  "uk.gov.hmrc"   %% "play-frontend-hmrc"              % "0.67.0-play-26",
Same as the others

2021-06-02 13:59 UTC, SheilaTran requested changes
Will has done such a good job reviewing! My only comment is to upgrade scalatest to 3.2.9 as it still compiles fine

2021-06-07 15:19 UTC, SheilaTran approved these changes

2021-06-07 15:19 UTC, merged